# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://marinegeo.github.io"
baseurl: ""
branch: "master"

# If you are building a GitHub project page then use these settings:
#url: "http://allbyend.github.io/marinegeo.github.io"
#baseurl: "/marinegeo.github.io"
#branch: "master"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: MarineGEO

# Short description of your site
description: Tools and resources for MarineGEO datasets

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Home: ""
  Habitats:
    - All: "modules.html"
    - Seagrass: "seagrass"
    - Reef - Coral: "coral-reefs"
    - Reef - Rocky: "rocky-reefs"
    - Reef - Oyster: "oyster-reefs"
    - Mangroves: "mangroves"
    - Sediment: "sediment"
  Experiments:
    - Panamex: "panamex"
  Resources:
    - Blog: "blog"
    - Standards: "standards"
    - Other Tools: "other-resources"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/MarineGEO_logo.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: "/img/Logomark_MarineGEO_Tennenbaum_RGB.png"
title-link: "https://marinegeo.si.edu"

## logo for logo in the footer
footer-logo: "/img/si-institution_logo-horizontal-clr.png"
footer-link: "https://www.si.edu"


## default thumbnail for Modules
default-thumbnail: /img/MarineGEO_logo.png

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#97C8EB" # "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#97C8EB"
footer-text-col: "#777777"
footer-link-col: "#404040"


# marinegeo colors
# dark blue = #0D5387
# turquoise = 	#02BABA
# green = 	#A7CE4E
# light blue = 	#C6E9FC

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

# move blog to another page rather than the home page
# https://github.com/daattali/beautiful-jekyll#how-do-i-move-the-blog-to-another-page-instead-of-having-it-on-the-home-page
paginate_path: "/blog/page:num/"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Marine Global Earth Observatory

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
#  rss: true
  email: "marinegeo-data@si.edu"
#  facebook: daattali
  github: marinegeo
  twitter: SImarineGEO
#  reddit: yourname
#  google-plus: +DeanAttali
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "MarineGEO.github.io"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-123255009-2"

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "marinegeo"

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

collections:
  project-modules:
    output: true
    permalink: /modules/:name

  module-groups:
    output: true
    permalink: /:name

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from




# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

habitat-links:
- path: /coral-reefs
  name: Coral
  color: 40E0D0
- path: /seagrass
  name: Seagrass
  color: 90EE90
- path: /Mangroves
  name: Mangroves
  color: DAA520
- path: /marshes
  name: Marshes
  color: F5DEB3
- path: /oyster-reefs
  name: Oyster Reefs
  color: 778899
- path: /Unstructured
  name: Unstructured
  color: A52A2A
- path: /environment
  name: Environment
  color: D3D3D3
- path: /experiments
  name: Experiments
  color: FF4500
